create table address
(
    address_id bigint generated by default as identity
        primary key,
    street     varchar(255)
);

create table client
(
    address_id  bigint
        unique
        constraint fk_address
            references address,
    client_id   bigint generated by default as identity
        primary key,
    client_name varchar(255)
);

create table phone
(
    client_id bigint not null
        constraint fk_client
            references client,
    phone_id  bigint generated by default as identity
        primary key,
    number    varchar(255)
);
