version: '3.0'

services:
  postgres:
    image: postgres:17
    container_name: pg-docker
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    ports:
      - "5430:5432"